spring:
  application:
    name: PlatformVaultS

  datasource:
    url: jdbc:h2:mem:platformvaults
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:ваш_токен_сюда}
    username: ${TELEGRAM_BOT_USERNAME:PlatformVaultsBot}

  miniapp:
    url: ${MINIAPP_URL:https://your-miniapp-url.com}

logging:
  level:
    com.platformvaults: DEBUG